spring:
  application:
    name: tlias-web-management
  #mysql连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: sqlsqlsql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl